### PR TITLE
remove governance proposal

### PR DESCRIPTION
**Pull request by puneet2019**
## 1. Overview
- removed register chain proposal.
- In x/lscosmos/keeper/governance_proposal.go:18-21, when handling a RegisterHostChainProposal, the guard ensures that HostChainParams are not already configured.
This implies that there is no way for governance to update existing HostChainParams. Also, since the administrator likely configures them within the JumpStart execution, this proposal will always fail.

## 2. Implementation details

- removes registerhostchain proposal

### CODE REVIEW

**Review by RohitAudit — COMMENTED** [review]
What governance proposal is this? Which oak error it refers to?

**Comment by puneet2019** [comment]
> What governance proposal is this? Which oak error it refers to?

We had a proposal to register chain/ put config on chain. (initialise the module) and we also had an admin function txn as a backup. It was an either-or usecase. So if one method initialises the module other is useless, hence we decided to remove proposal altogether

**Comment by RohitAudit** [comment]
> 

Was this functionality to enable liquid staking for any other chains? If we are removing the proposal method, does it mean that admin has to do the transaction to include the new chain?

**Comment by puneet2019** [comment]
> Was this functionality to enable liquid staking for any other chains? If we are removing the proposal method, does it mean that admin has to do the transaction to include the new chain

Yes! but the module is allowed to only register one chain( this one was meant for atom). and basically now the admin has to do it, rather than proposal.

**Comment by RohitAudit** [comment]
> > Was this functionality to enable liquid staking for any other chains? If we are removing the proposal method, does it mean that admin has to do the transaction to include the new chain
> 
> Yes! but the module is allowed to only register one chain( this one was meant for atom). and basically now the admin has to do it, rather than proposal.

Got it!!

**Review by RohitAudit — COMMENTED** [review]
Approved

**Review by RohitAudit — APPROVED** [review]
approved

**Pull request merged**
